### ISSUE TITLE
WooCommerce 3.2.1 + WordPress 4.8.2

### ISSUE THREAD

**Issue by tjwoon** [MOLPay/WordPress_WooCommerce_WP-eCommerce_ClassiPress#14]
Hi,

According to the [docs](https://github.com/MOLPay/WordPress_WooCommerce_WP-eCommerce_ClassiPress/wiki/Installation-for-WooCommerce-Plugins), you support the following versions of WooCommerce and WordPress:

- WooCommerce version 2.6.x WP 4.7.x and above
- WooCommerce version 2.3.x WP 4.1.x and above
- WooCommerce version 2.2.x WP 4.0.x and above
- WooCommerce version 2.1.x WP 3.8.x and above

I am using:

- WooCommerce 3.2.1
- WP 4.8.2

The WooCommerce version is a whole major version ahead of your newest supported version... Will it work?

Thanks & Regards,
TJ

**Comment by apis17** [comment]
Hi tjwoon,

Development team will check for v3.2.1

Thank you.

**Comment by tjwoon** [comment]
Hi @apis17 . Thank you 😊 Hope for good news soon

**Comment by tjwoon** [comment]
Hi,

I just tried this and it works fine: [WooCommerce] (https://github.com/MOLPay/WordPress/blob/master/dist/woocommerce-molpay.zip?raw=true)

Thanks!
