### ISSUE TITLE
woocommerce_molpay_seamless plugin clashes with WPLMS theme 

### ISSUE THREAD

**Issue by serefina** [MOLPay/WordPress_WooCommerce_WP-eCommerce_ClassiPress#18]
Hi, as I checkout with MOLPAY, page got stuck with infinite loading:
![image](https://user-images.githubusercontent.com/13086363/63825561-df927580-c98d-11e9-9d0a-d4da2eadd80b.png)

Here is the error from console window:
![image](https://user-images.githubusercontent.com/13086363/63825496-9a6e4380-c98d-11e9-916f-e4f874ef8530.png)

Here is the script directed by console window:
![image](https://user-images.githubusercontent.com/13086363/63825525-ba9e0280-c98d-11e9-8f01-756129dc8941.png)

I did not install ordering plugin since it is optional, but I have gone through all steps properly.
Could it be there is a clash of javascript?

Thanks.

**Comment by chenyaau94** [comment]
Hi @serefina , upon checking. This happens due to jQuery library been loaded twice. May refer the fix from the following discussion.
https://stackoverflow.com/questions/47346965/wordpress-media-library-not-working-mediaelementplayer-is-not-a-function
https://stackoverflow.com/questions/7882374/how-do-i-implement-jquery-noconflict

**Comment by serefina** [comment]
Thank you!

Regards,
Emily

On 30 Aug 2019, at 13:18, chenyaau94 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @serefina<https://github.com/serefina> , upon checking. This happens due to jQuery library been loaded twice. May refer the fix from the following discussion.
https://stackoverflow.com/questions/47346965/wordpress-media-library-not-working-mediaelementplayer-is-not-a-function
https://stackoverflow.com/questions/7882374/how-do-i-implement-jquery-noconflict

**Comment by chenyaau94** [comment]
Close as issue resolve.
