### ISSUE TITLE
Guided Notifications Broken Url to Setup MOLPay Merchant ID and Verify Key

### ISSUE THREAD

**Issue by masoudhaghi** [MOLPay/WordPress_WooCommerce_WP-eCommerce_ClassiPress#6]
One install the MOLPay WooCommerce plugin from dist/woocommerce-molpay.zip WordPress Notify the user to update the Merchant ID and Verify Key in the Gateway tab and the links are pointing to:
```
http://wordpress-site.com/wp-admin/admin.php?page=woocommerce_settings&tab=payment_gateways&section=WC_Molpay_Gateway
```

Once click on these links, the message display to notify the user that "You do not have sufficient permissions to access this page."
The correct URL should be as follow:
```
http://wordpress-site.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wc_molpay_gateway
```

WordPress 4.3.1
WooCommerce 2.4.7

**Comment by mohdhafeezjohari** [comment]
Hi masoudhaghi,

We already update the URL to point to the correct pages. Thanks for notify us about this issue.

Sorry for inconvenience caused.
